[package]
name = "slp-archive-cleaner"
description = "filter out cpu matches and handwarmers from tournament slippi replay archives"
version = "0.1.0"
edition = "2024"

[dependencies]
peppi = "2.0.1"
walkdir = "2.5.0"
